# Generated by Django 5.1.5 on 2025-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('testing', 'Testing'), ('documentation', 'Documentation'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
